name: Release
# Prepares a release and packages of Storm

on:
  # needed to trigger the workflow manually
  workflow_dispatch:

env:
  # GitHub runners currently have 4 cores
  NR_JOBS: "4"

jobs:
  debian: 
    name: Debian package (${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["debian-12", "ubuntu-24.04"]
        buildType: ["Release"]
    steps:
      - name: Git clone
        uses: actions/checkout@v4
      - name: Build storm from Dockerfile
        run: |
          docker build -t movesrwth/storm:ci . \
            --build-arg BASE_IMAGE=movesrwth/storm-basesystem:${{ matrix.distro }} \
            --build-arg build_type="${{ matrix.buildType }}" \
            --build-arg carl_tag="master" \
            --build-arg cmake_args="-DSTORM_BUILD_TESTS=OFF" \
            --build-arg no_threads=${NR_JOBS}
            # Omitting arguments developer, disable_*, cln_exact, cln_ratfunc, all_sanitizers
      - name: Run Docker
        run: docker run -d -it --name ci movesrwth/storm:ci
      - name: Run storm
        run: docker exec ci bash -c "/opt/storm/build/bin/storm --version"
      - name: Check compile flags
        uses: ./.github/actions/check-compile-flags-action
        with:
          buildType: ${{ matrix.buildType }}
          docker: true
      - name: Create package
        run: docker exec ci bash -c "cd /opt/storm/build; make package"
      - name: Copy package
        run: |
          docker exec ci bash -c "mkdir /opt/package; cp /opt/storm/build/*.deb /opt/package/"
          docker cp ci:/opt/package .
      - uses: actions/upload-artifact@v4
        with:
          name: storm-deb-${{ matrix.distro }}
          path: ./*.deb
