name: Update carl-storm version

on:
  # needed to reuse the workflow from another one
  workflow_call:
    inputs:
      carl_version:
        description: 'Carl-storm version'
        required: true
        type: string
        default: 'x.y'
  # needed to trigger the workflow manually
  workflow_dispatch:
    inputs:
      carl_version:
        description: 'Carl-storm version'
        required: true
        type: string
        default: 'x.y'

  update_storm:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Git clone
        uses: actions/checkout@v5
      - name: Update carl-storm version
        run: |
          # Update STORM_CARL_GIT_TAG
          sed -i -E 's/STORM_CARL_GIT_TAG "(.*)" "[0-9]+\.[0-9]+"\)/STORM_CARL_GIT_TAG "\1" "${{ inputs.carl_version }}"\)/' CMakeLists.txt
          # Update carl_tag
          sed -i -E 's/ARG carl_tag="[0-9]+\.[0-9]+"/ARG carl_tag="${{ inputs.carl_version }}"/' Dockerfile
          sed -i -E 's/ARG carl_tag="[0-9]+\.[0-9]+"/ARG carl_tag="${{ inputs.carl_version }}"/' .github/workflows/Dockerfile.archlinux
      - name: Commit update
        run: |
          git diff
          git config user.name 'Stormchecker bot'
          git config user.email 'dev@stormchecker.org'
          git commit -am "Use carl-storm ${{ inputs.carl_version }}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          branch: ci/update-carl-storm
          delete-branch: true
          title: 'Update carl-storm ${{ inputs.carl_version }}'
          body: |
            Auto-generated pull request triggered by a new carl-storm version.
            - Manually close and reopen this PR to trigger the CI.
